<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsClientProject>true</IsClientProject>
    <ServerDllName>AgentHub.Server</ServerDllName>
    <AssetUrlPrefix>/modules/AgentHub</AssetUrlPrefix>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Oqtane.Client\Oqtane.Client.csproj" />
  </ItemGroup>

</Project>
